#!/usr/bin/env python3
"""Audit MAGICAL source files related to PDK, GDS export, and pin output.

This script is intentionally read-only. It scans source text for keywords and
emits a markdown index for native Sky130 export planning.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "docs/sky130_adapter/native_sky130_export_flow_audit.md"

KEYWORD_GROUPS = {
    "GDS export": [
        "writeGds",
        "writeLayoutGds",
        "GdsWriter",
        "writeRectangle",
        "addRoutingLayout",
        "addBox2Cell",
        "addTxt2Cell",
        "addText2Cell",
        "gds_write_layer",
        "gds_write_datatype",
        "addPolygon",
        "addText",
    ],
    "techfile / TechDB": [
        "techfile",
        "simple_tech_file",
        "parseSimpleTechFile",
        "TechDB",
        "addNewLayer",
        "dbLayerToPdk",
        "pdkLayerToDb",
        "TechfileReader",
        "TECHLAYER",
    ],
    "LEF / routing rules": [
        "parseLef",
        "LefReader",
        "LefDB",
        "lef_layer_cbk",
        "parseRoutingLayer",
        "parseCutLayer",
        "routingLayer",
        "cutLayer",
        "via",
    ],
    "ioPin / pin / TEXT": [
        "ioPin",
        "writeDumb",
        "DumbWriter",
        "writeiopifile",
        "IOPinReader",
        "setIOPort",
        "bIOPort",
        "TEXT",
        "TEXTTYPE",
        "addText",
    ],
    "power nets": [
        "vddNetNames",
        "vssNetNames",
        "markPowerNets",
        "markVddFlag",
        "markVssFlag",
        "isPower",
        "powerLayer",
    ],
}

SKIP_DIRS = {
    ".git",
    "__pycache__",
    "generated",
    "build",
}

SOURCE_SUFFIXES = {
    ".py",
    ".cpp",
    ".hpp",
    ".h",
    ".cc",
    ".cxx",
    ".c",
    ".md",
    ".json",
    ".lef",
    ".techfile",
}


@dataclass(frozen=True)
class Hit:
    path: Path
    line_no: int
    line: str
    keyword: str


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def iter_source_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.suffix in SOURCE_SUFFIXES or path.name.endswith(".techfile.simple"):
            files.append(path)
    return sorted(files)


def scan_file(path: Path, keywords: list[str]) -> list[Hit]:
    hits: list[Hit] = []
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except Exception:
        return hits
    lowered_keywords = [(keyword, keyword.lower()) for keyword in keywords]
    for line_no, line in enumerate(lines, start=1):
        lowered = line.lower()
        for keyword, lowered_keyword in lowered_keywords:
            if lowered_keyword in lowered:
                hits.append(Hit(path=path, line_no=line_no, line=line.strip(), keyword=keyword))
                break
    return hits


def classify_files(files: list[Path]) -> dict[str, list[Hit]]:
    grouped: dict[str, list[Hit]] = {}
    for group, keywords in KEYWORD_GROUPS.items():
        hits: list[Hit] = []
        for path in files:
            hits.extend(scan_file(path, keywords))
        grouped[group] = hits
    return grouped


def summarize_files(hits: list[Hit]) -> list[tuple[Path, int, str]]:
    by_file: dict[Path, list[Hit]] = {}
    for hit in hits:
        by_file.setdefault(hit.path, []).append(hit)
    summary: list[tuple[Path, int, str]] = []
    for path, file_hits in sorted(by_file.items(), key=lambda item: rel(item[0])):
        keywords = sorted({hit.keyword for hit in file_hits})
        summary.append((path, len(file_hits), ", ".join(keywords[:8])))
    return summary


def render(grouped: dict[str, list[Hit]]) -> str:
    lines = [
        "# Native Sky130 Export Flow Audit",
        "",
        "This audit is generated by `tools/sky130_adapter/audit_magical_pdk_export_flow.py`.",
        "It is a read-only source index for planning native Sky130 export. It does not modify MAGICAL source.",
        "",
        "## High-Confidence Source Locations",
        "",
        "| Area | Candidate files |",
        "| --- | --- |",
        "| GDS route export | `anaroute/src/writer/wrLayout.cpp`, `anaroute/src/writer/wrGds.cpp`, `anaroute/src/writer/writer.cpp`, `flow/python/PnR.py` |",
        "| Device/placement GDS export | `flow/cpp/magical_flow/src/writer/GdsWriter.h`, `flow/python/Flow.py`, `flow/python/PnR.py` |",
        "| TechDB/simple techfile | `flow/python/MagicalDB.py`, `flow/cpp/magical_flow/src/db/TechDB.h`, `flow/cpp/magical_flow/src/parser/ParseSimpleTech.cpp` |",
        "| Anaroute techfile/LEF | `anaroute/src/parser/parTech.cpp`, `anaroute/src/db/dbTechfile.hpp`, `anaroute/src/parser/parLef.cpp`, `anaroute/src/db/dbLef.hpp` |",
        "| ioPin/debug pin output | `flow/python/PnR.py`, `anaroute/src/writer/wrDumb.cpp`, `anaroute/src/parser/parIOPin.cpp` |",
        "| Power-net propagation | `flow/python/Params.py`, `flow/python/MagicalDB.py`, `flow/python/PnR.py` |",
        "",
        "## Keyword Scan Summary",
        "",
    ]
    for group, hits in grouped.items():
        lines.extend([f"### {group}", "", "| file | hits | example keywords |", "| --- | ---: | --- |"])
        for path, count, keywords in summarize_files(hits)[:40]:
            lines.append(f"| `{rel(path)}` | {count} | {keywords} |")
        if not hits:
            lines.append("| (none) | 0 | |")
        lines.append("")

    lines.extend(
        [
            "## Focused Findings",
            "",
            "- `flow/python/MagicalDB.py` reads the JSON-selected netlist and simple techfile, then marks power nets from `vddNetNames` / `vssNetNames`.",
            "- `flow/python/PnR.py` invokes Anaroute with `parseLef`, `parseTechfile`, `parseGds`, `writeLayoutGds`, and `writeDumb`.",
            "- `anaroute/src/writer/wrLayout.cpp` merges placement GDS with routing geometry and writes final `*.route.gds`; this is the most direct native export hook for route shapes and route TEXT.",
            "- `anaroute/src/writer/wrLayout.cpp` currently writes routing polygons using `maskIdx = _cir.layerIdx2MaskIdx(...)` and datatypes `0` or `40`; route IO text uses `100 + maskIdx` and no Sky130 TEXTTYPE.",
            "- `flow/cpp/magical_flow/src/writer/GdsWriter.h` writes layout rectangles through `TechDB::dbLayerToPdk` and preserves per-rectangle datatype; it also writes TEXT with skipped datatype/texttype semantics.",
            "- `anaroute/src/writer/wrDumb.cpp` writes the `*.ioPin` file from all routed nets, choosing one box/layer per net. It does not know the original top subckt port list.",
            "- `tools/sky130_adapter/remap_gds_to_sky130.py` is currently an external binary GDS layer/datatype remapper; its responsibility belongs near native GDS export, not in Magic/LVS scripts.",
            "- `tools/sky130_adapter/add_sky130_pin_labels_from_iopin.py` and `add_sky130_pin_shapes_from_iopin.py` currently compensate for missing native Sky130 pin-purpose/text export.",
            "",
            "## Notes",
            "",
            "- This audit intentionally avoids editing `flow/python/DesignDB.py`, Anaroute, device generation, or PDK examples.",
            "- `generated/` is skipped during source scanning so previous regression outputs do not dominate the index.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit MAGICAL PDK/GDS export flow sources.")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    files = iter_source_files(args.repo_root.resolve())
    grouped = classify_files(files)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(grouped), encoding="utf-8")
    print(f"scanned_files={len(files)}")
    for group, hits in grouped.items():
        print(f"{group}: hits={len(hits)} files={len(summarize_files(hits))}")
    print(f"output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
