#!/usr/bin/env python3
"""Generate a MAGICAL-compatible trial sky130PDK.

MAGICAL currently treats the numeric IDs in techfile/simple techfile as
internal PDK layer IDs and requires them to be added in ascending order. This
generator therefore preserves the mockPDK internal numbers and records real
Sky130 GDS layer/datatype mappings in a separate export map.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - depends on local environment.
    yaml = None


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LAYER_MAP = REPO_ROOT / "docs/sky130_adapter/sky130_layer_map.yaml"
DEFAULT_INPUT_DIR = REPO_ROOT / "examples/sky130PDK"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "generated/sky130PDK_trial"


@dataclass(frozen=True)
class LayerRecord:
    magical_layer: str
    magical_internal_number: int
    sky130_layer_name: str
    sky130_gds_layer: str
    sky130_datatype: str
    status: str
    risk: str
    datatype_overrides: dict[str, Any] = field(default_factory=dict)


def is_tbd(value: Any) -> bool:
    if value is None:
        return True
    text = str(value).strip()
    return text == "" or text.upper() in {"TBD", "UNKNOWN", "NONE"}


def load_layer_map(path: Path) -> dict[str, dict[str, Any]]:
    if yaml is None:
        raise RuntimeError(
            "PyYAML is required to read sky130_layer_map.yaml. "
            "Install python3-yaml or run in the existing MAGICAL environment."
        )
    with path.open("r", encoding="utf-8") as fp:
        data = yaml.safe_load(fp)
    if not isinstance(data, dict) or not isinstance(data.get("layers"), dict):
        raise RuntimeError(f"Invalid layer map format: {path}")
    return data["layers"]


def make_record(
    layer: str,
    internal_number: int,
    layer_map: dict[str, dict[str, Any]],
) -> LayerRecord:
    info = layer_map.get(layer, {})
    sky130_layer_name = str(info.get("selected_sky130_layer", "TBD"))
    sky130_gds_layer = str(info.get("gds_layer", "TBD"))
    sky130_datatype = str(info.get("datatype", "TBD"))
    status = "tbd" if (
        not info
        or is_tbd(sky130_layer_name)
        or is_tbd(sky130_gds_layer)
        or is_tbd(sky130_datatype)
    ) else "confirmed"

    return LayerRecord(
        magical_layer=layer,
        magical_internal_number=internal_number,
        sky130_layer_name=sky130_layer_name,
        sky130_gds_layer=sky130_gds_layer,
        sky130_datatype=sky130_datatype,
        status=status,
        risk=str(info.get("risk", "TBD")),
        datatype_overrides=datatype_overrides(info),
    )


def datatype_overrides(info: dict[str, Any]) -> dict[str, Any]:
    raw = info.get("datatype_overrides", {})
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, list):
        overrides: dict[str, Any] = {}
        for item in raw:
            if not isinstance(item, dict):
                continue
            input_datatype = item.get("input_datatype")
            if input_datatype is None:
                continue
            overrides[str(input_datatype)] = {
                key: value for key, value in item.items() if key != "input_datatype"
            }
        return overrides
    return {}


def annotation(record: LayerRecord) -> str:
    if record.status == "confirmed":
        return (
            f"sky130_export={record.sky130_layer_name} "
            f"{record.sky130_gds_layer}/{record.sky130_datatype}"
        )
    return "sky130_export=TBD"


def rewrite_simple_tech(
    text: str,
    layer_map: dict[str, dict[str, Any]],
) -> tuple[str, list[LayerRecord]]:
    records: list[LayerRecord] = []
    output: list[str] = []
    pattern = re.compile(r"^(\s*)(\S+)(\s+)(\d+)(.*)$")

    for line in text.splitlines():
        match = pattern.match(line)
        if not match:
            output.append(line)
            continue
        indent, layer, spacing, number, _rest = match.groups()
        record = make_record(layer, int(number), layer_map)
        records.append(record)
        output.append(
            f"{indent}{layer}{spacing}{number}  # SKY130_ADAPTER: "
            f"internal layer id preserved; {annotation(record)}"
        )

    return "\n".join(output) + "\n", records


def rewrite_techfile(
    text: str,
    layer_map: dict[str, dict[str, Any]],
    simple_numbers: dict[str, int] | None = None,
) -> tuple[str, list[LayerRecord]]:
    records: list[LayerRecord] = []
    output: list[str] = [
        "; Generated by tools/sky130_adapter/generate_magical_sky130_pdk.py",
        "; MAGICAL internal layer IDs are preserved for TechDB ordering.",
        "; Real Sky130 GDS layer/datatype mappings are recorded in sky130_gds_export_map.yaml.",
    ]
    pattern = re.compile(r"^(\s*\(\s*)(\S+)(\s+)(\d+)(\s+)(\S+)(\s*\).*)$")

    for line in text.splitlines():
        match = pattern.match(line)
        if not match:
            output.append(line)
            continue
        prefix, layer, spacing_a, number, spacing_b, abbrev, suffix = match.groups()
        record = make_record(layer, int(number), layer_map)
        records.append(record)
        output.append(
            f"{prefix}{layer}{spacing_a}{number}{spacing_b}{abbrev}{suffix}"
            f" ; SKY130_ADAPTER: internal layer id preserved; {annotation(record)}"
        )

    return "\n".join(output) + "\n", records


def rewrite_lef(
    text: str,
    layer_map: dict[str, dict[str, Any]],
    internal_numbers: dict[str, int],
) -> tuple[str, list[LayerRecord]]:
    records: list[LayerRecord] = []
    output: list[str] = [
        "# Generated by tools/sky130_adapter/generate_magical_sky130_pdk.py",
        "# MAGICAL LEF layer names and mock routing geometry are preserved.",
        "# Real Sky130 GDS layer/datatype mappings are recorded in sky130_gds_export_map.yaml.",
    ]
    pattern = re.compile(r"^(\s*)LAYER\s+(\S+)\s*$")

    for line in text.splitlines():
        match = pattern.match(line)
        if not match:
            output.append(line)
            continue
        _indent, layer = match.groups()
        record = make_record(layer, internal_numbers.get(layer, -1), layer_map)
        records.append(record)
        output.append(f"# SKY130_ADAPTER: {annotation(record)}")
        output.append(line)

    return "\n".join(output) + "\n", records


def read_simple_numbers(simple_text: str) -> dict[str, int]:
    numbers: dict[str, int] = {}
    pattern = re.compile(r"^\s*(\S+)\s+(\d+)\b")
    for line in simple_text.splitlines():
        match = pattern.match(line)
        if match:
            numbers[match.group(1)] = int(match.group(2))
    return numbers


def export_records(records: list[LayerRecord]) -> str:
    unique: dict[str, LayerRecord] = {}
    for record in records:
        if record.magical_layer not in unique:
            unique[record.magical_layer] = record

    data = {
        "schema_version": 0.1,
        "status": "draft",
        "purpose": (
            "Map MAGICAL internal layer IDs to real Sky130 GDS layer/datatype "
            "for a future export remap or post-processing step."
        ),
        "layers": [],
    }
    for record in sorted(unique.values(), key=lambda item: item.magical_internal_number):
        entry = {
            "magical_layer": record.magical_layer,
            "magical_internal_number": record.magical_internal_number,
            "sky130_layer_name": record.sky130_layer_name,
            "sky130_gds_layer": record.sky130_gds_layer,
            "sky130_datatype": record.sky130_datatype,
            "status": record.status,
            "risk": record.risk,
        }
        if record.datatype_overrides:
            entry["datatype_overrides"] = record.datatype_overrides
        data["layers"].append(entry)
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


def write_lf(path: Path, text: str) -> None:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    with path.open("w", encoding="utf-8", newline="\n") as fp:
        fp.write(text)


def print_summary(records: list[LayerRecord], output_dir: Path, dry_run: bool) -> None:
    unique: dict[str, LayerRecord] = {}
    for record in records:
        unique.setdefault(record.magical_layer, record)

    confirmed = [record for record in unique.values() if record.status == "confirmed"]
    tbd = [record for record in unique.values() if record.status == "tbd"]
    mode = "DRY-RUN" if dry_run else "WROTE"

    print(f"[{mode}] trial PDK output directory: {output_dir}")
    print()
    print("MAGICAL internal tech layer preserved:")
    print(f"  layers in generated techfile/simple/lef keep their mockPDK internal IDs")
    print(f"  unique MAGICAL layers recorded: {len(unique)}")
    print()
    print("Sky130 GDS export mapping recorded separately:")
    print("  generated file: sky130_gds_export_map.yaml")
    print(f"  confirmed sky130 mappings: {len(confirmed)}")
    print(f"  TBD sky130 mappings: {len(tbd)}")
    if tbd:
        names = ", ".join(record.magical_layer for record in sorted(tbd, key=lambda item: item.magical_layer))
        print(f"  TBD layers: {names}")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate MAGICAL-compatible trial sky130PDK files."
    )
    parser.add_argument("--dry-run", action="store_true", help="Print planned output without writing files.")
    parser.add_argument("--layer-map", type=Path, default=DEFAULT_LAYER_MAP, help="Path to sky130_layer_map.yaml.")
    parser.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT_DIR, help="Input sky130PDK skeleton directory.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Output trial PDK directory.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    layer_map_path = args.layer_map.resolve()
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()

    try:
        layer_map = load_layer_map(layer_map_path)
        simple_path = input_dir / "sky130.techfile.simple"
        techfile_path = input_dir / "sky130.techfile"
        lef_path = input_dir / "sky130.lef"
        for path in (simple_path, techfile_path, lef_path):
            if not path.is_file():
                raise FileNotFoundError(path)

        simple_text = simple_path.read_text(encoding="utf-8")
        simple_numbers = read_simple_numbers(simple_text)
        generated_simple, simple_records = rewrite_simple_tech(simple_text, layer_map)
        generated_techfile, techfile_records = rewrite_techfile(
            techfile_path.read_text(encoding="utf-8"), layer_map, simple_numbers
        )
        generated_lef, lef_records = rewrite_lef(
            lef_path.read_text(encoding="utf-8"), layer_map, simple_numbers
        )
        all_records = simple_records + techfile_records + lef_records
        generated_export_map = export_records(all_records)

        print_summary(all_records, output_dir, args.dry_run)
        if args.dry_run:
            print()
            print("Dry-run only: no files were written.")
            return 0

        output_dir.mkdir(parents=True, exist_ok=True)
        write_lf(output_dir / "sky130.techfile.simple", generated_simple)
        write_lf(output_dir / "sky130.techfile", generated_techfile)
        write_lf(output_dir / "sky130.lef", generated_lef)
        write_lf(output_dir / "sky130_gds_export_map.yaml", generated_export_map)

        print()
        print("Generated files:")
        print(f"  {output_dir / 'sky130.techfile'}")
        print(f"  {output_dir / 'sky130.techfile.simple'}")
        print(f"  {output_dir / 'sky130.lef'}")
        print(f"  {output_dir / 'sky130_gds_export_map.yaml'}")
        return 0
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
